version: '2.8'

services:
  postgres:
    image: docker-hub.pigeon-server.cn/library/postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: 'sm_sys_data'
      POSTGRES_USER: 'ServerManager'
      POSTGRES_PASSWORD: 'ServerManager'
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: docker-hub.pigeon-server.cn/library/redis:latest
    container_name: redis
    networks:
      - backend

  django_app:
    build:
      context: .  # Dockerfile 的上下文路径
      dockerfile: Dockerfile.x86  # 指定要使用的 Dockerfile
    container_name: django_app
    environment:
      DEBUG: 'False'
      DJANGO_SETTINGS_MODULE: 'LoongArch-ServerManager.settings'
      DATABASE_URL: 'postgres://ServerManager:ServerManager@postgres:5432/sm_sys_data'
      REDIS_URL: 'redis://redis:6379'
    links:
      - redis
      - postgres
    depends_on:
      - postgres
      - redis
    networks:
      - backend


  nginx:
    image: docker-hub.pigeon-server.cn/library/nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # 你需要在项目根目录创建nginx.conf文件
      - ./static:/ServerManager/static
    links:
      - django_app
    ports:
      - "80:80"
      - '443:443'
    depends_on:
      - django_app
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
  frontend:
