FROM docker-hub.pigeon-server.cn/library/python:slim-bullseye
LABEL authors="fsj"

EXPOSE 8000

USER root

RUN apt update

RUN apt install gcc libpq-dev libmagic1

COPY . /app

WORKDIR /app

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN pip install -r ./requirements.txt

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000", "--noreload"]