# Generated by Django 4.2.13 on 2024-06-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission_groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='权限组名')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('disable', models.BooleanField(null=True, verbose_name='是否禁用')),
            ],
            options={
                'db_table': 'permission_group_list',
                'db_table_comment': '权限组列表',
            },
        ),
        migrations.CreateModel(
            name='Permission_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='权限项ID')),
                ('permission', models.CharField(max_length=30, unique=True, verbose_name='权限名')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='权限项介绍')),
                ('translate', models.CharField(max_length=30, null=True, unique=True, verbose_name='权限翻译')),
            ],
            options={
                'db_table': 'permission_item',
                'db_table_comment': '权限项',
            },
        ),
    ]
