# Generated by Django 4.2.13 on 2024-06-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission_manager', '0001_initial'),
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_groups',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_manager.user'),
        ),
        migrations.AddField(
            model_name='permission_groups',
            name='permissions',
            field=models.ManyToManyField(related_name='groups_permission_mapping', to='permission_manager.permission_item'),
        ),
    ]
