# Generated by Django 4.2.13 on 2024-06-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Settings', models.CharField(max_length=120, unique=True, verbose_name='设置项名')),
                ('value', models.CharField(max_length=4096, verbose_name='值')),
                ('lastModifiedTime', models.DateTimeField(auto_now=True, null=True, verbose_name='上次修改时间')),
                ('lastModifiedUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_manager.user')),
            ],
            options={
                'db_table': 'setting',
                'db_table_comment': '设置',
            },
        ),
    ]
