# Generated by Django 4.2.13 on 2024-06-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='IP地址')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('module', models.CharField(max_length=512, verbose_name='访问的模块')),
            ],
            options={
                'db_table': 'access_log',
                'db_table_comment': '访问日志',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('action', models.CharField(max_length=256, verbose_name='动作')),
                ('module', models.CharField(max_length=256, verbose_name='模块')),
                ('content', models.CharField(max_length=4096, verbose_name='数据')),
            ],
            options={
                'db_table': 'audit',
                'db_table_comment': '审计',
            },
        ),
        migrations.CreateModel(
            name='FileChange_Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('action', models.CharField(max_length=512, verbose_name='动作')),
                ('filepath', models.CharField(max_length=4096, verbose_name='目标文件')),
            ],
            options={
                'db_table': 'file_change_log',
                'db_table_comment': '文件修改记录',
            },
        ),
        migrations.CreateModel(
            name='System_Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('level', models.IntegerField(verbose_name='日志等级')),
                ('module', models.CharField(max_length=256, verbose_name='模块')),
                ('content', models.CharField(max_length=1024, verbose_name='日志内容')),
            ],
            options={
                'db_table': 'system_log',
                'db_table_comment': '系统日志',
            },
        ),
    ]
