# Generated by Django 4.2.13 on 2024-06-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechange_log',
            name='user',
            field=models.ForeignKey(db_column='用户', on_delete=django.db.models.deletion.DO_NOTHING, to='user_manager.user'),
        ),
        migrations.AddField(
            model_name='audit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_manager.user'),
        ),
        migrations.AddField(
            model_name='access_log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_manager.user'),
        ),
    ]
