# Generated by Django 4.2.13 on 2024-06-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('userName', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('realName', models.CharField(max_length=32, null=True, unique=True, verbose_name='姓名')),
                ('email', models.EmailField(max_length=100, null=True, unique=True, verbose_name='电子邮箱')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('lastLoginTime', models.DateTimeField(auto_now=True, null=True, verbose_name='上次登录时间')),
                ('lastLoginIP', models.GenericIPAddressField(null=True, verbose_name='上次登录IP')),
                ('password', models.CharField(max_length=128, verbose_name='密码(md5)')),
                ('passwordSalt', models.CharField(max_length=128, unique=True, verbose_name='密码盐')),
                ('avatar', models.CharField(max_length=64, null=True, verbose_name='头像hash')),
                ('disable', models.BooleanField(default=False, null=True, verbose_name='是否禁用')),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permission_manager.permission_groups')),
            ],
            options={
                'db_table': 'users',
                'db_table_comment': '用户',
            },
        ),
    ]
